### ISSUE TITLE
[Buildmaster] doesn't build yab and yab-ide for 64 bit haiku.

### ISSUE THREAD

**Issue by bbjimmy** [haikuports/haikuporter#138] opened 2017-09-26 18:21 UTC
The recipes are good, and one can build these for x86_64, but the Buildmaster only supplies the source packages.

**Comment by bbjimmy** [comment] 2017-09-29 20:57
Just re-tested, yab and yab_ide both build just fine on hrev51439 x86_64

**Comment by bbjimmy** [comment] 2017-10-01 15:16
As of hrev51449 yab is broken.
in hrev51449 BControlLook was changed. The un released change to yab that added the tabs on the side removed the reliance on BControlLook. So until I get another release done this issue is on hold.

**Comment by bbjimmy** [comment] 2017-10-11 16:06
yab is now 1.7.5.5 and yab-ide 2.2.8a the BControlLook was change is fixed.

**Comment by mmlr** [comment] 2017-10-15 21:13
For the record: The buildmasters didn't build them because it ran in update mode since I set them up at the end of July. Only ports for which files are changed get built in this mode. Separate buildruns will be scheduled to introduce missing packages later on. This is not a bug in either the buildmaster nor the recipes, therefore closing this issue.

**Closed by mmlr** 2017-10-15 21:13 UTC
