### ISSUE TITLE
Add a "build number" to built packages separate from recipe REVISION

### ISSUE THREAD

**Issue by waddlesplash** [haikuports/haikuporter#164] opened 2018-08-01 22:00 UTC
Presently, we have one "revision" field that we control separate from the actual package version: REVISION. This has been used to identify both actual recipe changes as well as the need for a rebuild, which leads to headaches when it comes to library updates that break ABI but not source API, and then implicitly to #158. In these cases, the HaikuPorts recipe repository remains fully consistent before and after such an upgrade; but the binary repository will obviously now be broken.

Presently we have been [manually bumping recipe REVISIONs](https://github.com/haikuports/haikuporter/blob/master/tools/bump-revisions-of-dependents.sh) to force rebuilds. This is obviously problematic for a number of reasons (timing dependent, prone to failure, etc.) and there remains contention over whether it should be done at all.

Instead, we should add a "build number" to packages, so that instead of instead of the built package having a full name something like `pkg-4.7-1` it will become `-4.7-1.1, -1.2`, etc. When a recipe's revision is bumped, it should be rebuilt (as build-number `1`, of course), and then all packages that have one of this first package's `PROVIDES` in their `BUILD_REQUIRES`, we should rebuild with an incremented build number. Under this method, the HaikuPorts recipe repository is more disconnected from the packages it produces, but I think in the long term this will be a good thing.

This was already discussed / brainstormed with @alaviss and @pulkomandy [on IRC](https://echelog.com/logs/browse/haiku/1532728800); so @mmlr, @fbrosson, @korli if you could please weigh in, that would be great.

**Comment by mmlr** [comment] 2018-08-02 06:10
First off, this approach has already been discussed before and was ultimately not implemented.

Honestly, I don't see this as needed or desireable. If I underatand the proposal correctly, it would mean that all dependent packages would always be rebuilt. This would simply waste a lot of resources in most cases without an actual need. Think about a security update to libpng or something often used as that. Also note that this will cause users to download these new packages needlessly and therefore amplifies the resource waste and distributes it further onto the whole infrastructure. This is especially problematic because larger ports, which tend to have lots of dependencies, would be hit by that proportionally more often and this would quickly become less feasible resource wise.

Such rebuilds are only necessary when there is some form of breakage happening (API, ABI, provides declaration), which is not the usual case. Minor bumps are not running into this and most of the regular maintenence revolves around these.

My opinion on this is the same as the one in #158 because the discussion is ultimately the same: Explicit is better than implicit. When things change in a breaking way, the resulting new coherent package set should be tested and then explicitly recorded as fitting together by placing the correct version constraint.

I realize that an older version of a dependency can technically be perfectly compatible with a recipe and such a version constraint should then not be needed. But these version constraints simply do have a different meaning in such cases: They track what version of a dependency fits the resulting package. After all we manage the binary repository directly with these, so this makes sense.

Of course the binary repository and the source one could be decoupled. My opinion would then still stand however. If it were to be decoupled then I would still vote for a "configuration" or "package constraint record" that would have explicit version constraints and would need to be adjusted in such cases. Automatic rebuilds would again be wasteful and I am against that.

Either form of automatic rebuilds simply doesn't have enough information to tell if rebuilds are necessary or not. That is something only the person doing a version bump can judge. And the result of that evaluation should then be recorded into the constraints.

These discussions may make it seem that such bumping and rebuilding is a common case that will be needed for any minor update. But this is not the case at all. It really only concers the cases where a form of breakage happens. This has happened due to provides declaration adjustments in the past, which IMO are a structural problem and should be dealt with by more carefully choosing these declarations instead of "painting over" the issue by rebuilding lots of packages until something fits.

In the end, the whole point of the package management is to allow for fine grained and explicit declaration of (package) compatibility. These mechanisms should be used as such, which leads to a consistent repository. The "just rebuild everything that might touch this" approach with the reasoning of "the source repository is consistent" IMO defeats that point.

What I would on the other hand welcome would be to track such "rebuild only revbumps" separately per architecture. Because right now we often bump the revision due to an architecture (or architecture repo) specific issue and cause a rebuild for all other architectures where such a rebuild is not necessary at all. This is again wasteful and it would be nice to avoid.

**Comment by waddlesplash** [comment] 2018-08-02 13:10
OK, so we need HaikuPorter to provide some functionality to go through the tree and update the REQUIRES when doing major version bumps then.

**Comment by pulkomandy** [comment] 2018-08-02 13:26
I would prefer what mmlr suggested: adding explicit versions in recipes and bumping the revisions when you do this. No automated bumping and no useless rebuild of recipes. Only when a soname changes, then the dependencies need to be updated. It does not happen that often and it should be ok to have recipes continuing to use the old version, however we should also decide what to do in this case because we may end up with un-installable packages (because two packages depend on two different versions of a lib, and the two versions cannot be installed side by side).

So the plan of action would be:
- Patch libsolv to allow installing two versions of a package side by side, as long as the provides do not otherwise collide (this is not easy with the current way we define provides: lib:something = 1 does not conflict with lib:something = 2, but the matchin devel: entries most likely do)
- Stop using the trick of changing the package name to avoid the conflict (eg libpng12 vs libpng16 vs libpng15)
- Have recipes declare the range of versions they are tested with (it is not possible to say that a recipe will work with future and yet unreleased versions of a lib, so it makes no sense to not have a version constraint at all in recipes)

It then becomes a buildmaster policy wether to build a recipe against the whole supported range of dependencies, or just against the most recent supported version. The latter should be fine and keep our versionning as it was before.

Finally, we are left with libraries that do not declare a soname or forget to bump it on ABI changes. For these I don't know what can be done, except reporting to upstream or adding a soname ourselves (we did this eg. for Lua).

**Comment by waddlesplash** [comment] 2018-08-02 13:30
This is not just a libsolv issue; the entirety of Haiku's package management system assumes that you cannot install two versions of the same package. We need to keep the present system of using versions after the names. (Ubuntu does the same.)

**Comment by waddlesplash** [comment] 2018-08-02 13:33
Most of this process will be automated; i.e. there are some 20 recipes which depended on FFmpeg but they required only a rebuild after the ABI break. I don't want to edit those by hand, I want to just request that they be rebuilt and make sure they are and work after they are. That would ideally be 1-3 commands for me, not manually editing 20 files to update REQUIRES with new sonames. That's what I meant by a sub-tool of HaikuPorter is needed here.

**Comment by pulkomandy** [comment] 2018-08-02 13:37
IIRC the entirety of the package system was designed so we could install multiple versions of a package side by side, but then libsolv did not allow it and the idea has faded. It does make dependency solving more complex, however, because you may need to install multiple versions of a package, but you want to keep a minimal set of versions, still. (Ubuntu/Debian does it, but only for major API changes)

With this solved, the point is you don't need to rebuild all dependencies at once. It becomes possible to keep the old version of a package around for some time, until all dependencies are updated, tested, and recipes updated.

**Comment by waddlesplash** [comment] 2018-08-02 13:43
Then we should just change policy to add the major version to the package name when bumping without rebuilding all dependents.

**Comment by alaviss** [comment] 2018-08-03 08:16
@mmlr 

> Honestly, I don't see this as needed or desireable. If I underatand the proposal correctly, it would mean that all dependent packages would always be rebuilt. This would simply waste a lot of resources in most cases without an actual need. Think about a security update to libpng or something often used as that. Also note that this will cause users to download these new packages needlessly and therefore amplifies the resource waste and distributes it further onto the whole infrastructure. This is especially problematic because larger ports, which tend to have lots of dependencies, would be hit by that proportionally more often and this would quickly become less feasible resource wise.
>
> Such rebuilds are only necessary when there is some form of breakage happening (API, ABI, provides declaration), which is not the usual case. Minor bumps are not running into this and most of the regular maintenence revolves around these.

Yes, and this "form of breakage" is tracked with `compat` versions of a port, given that most library ports nowadays correctly declare their `compat` versions, we can base this feature on it.

> My opinion on this is the same as the one in #158 because the discussion is ultimately the same: Explicit is better than implicit. When things change in a breaking way, the resulting new coherent package set should be tested and then explicitly recorded as fitting together by placing the correct version constraint.
>
> I realize that an older version of a dependency can technically be perfectly compatible with a recipe and such a version constraint should then not be needed. But these version constraints simply do have a different meaning in such cases: They track what version of a dependency fits the resulting package. After all we manage the binary repository directly with these, so this makes sense.
>
> Of course the binary repository and the source one could be decoupled. My opinion would then still stand however. If it were to be decoupled then I would still vote for a "configuration" or "package constraint record" that would have explicit version constraints and would need to be adjusted in such cases. Automatic rebuilds would again be wasteful and I am against that.

From what I've seen, our ultimate goal after porting a new ABI/soname incompatible library version is to migrate all existing binaries to it, so it's safe to assume: a package will be fitted with the latest version of it's dependencies unless stated otherwise.

The testing will be done before anything could reach the `master` branch, ensuring that all packages are compatible with the newer libs, or have version constraints added to them if they can't be made compatible.

> Either form of automatic rebuilds simply doesn't have enough information to tell if rebuilds are necessary or not. That is something only the person doing a version bump can judge. And the result of that evaluation should then be recorded into the constraints.
>
> These discussions may make it seem that such bumping and rebuilding is a common case that will be needed for any minor update. But this is not the case at all. It really only concers the cases where a form of breakage happens. This has happened due to provides declaration adjustments in the past, which IMO are a structural problem and should be dealt with by more carefully choosing these declarations instead of "painting over" the issue by rebuilding lots of packages until something fits.

For minor update, where ABI compatibility is not broken, it's totally fine not to rebuild. I believe our `compat` declarations are already more than enough to track this.

> In the end, the whole point of the package management is to allow for fine grained and explicit declaration of (package) compatibility. These mechanisms should be used as such, which leads to a consistent repository. The "just rebuild everything that might touch this" approach with the reasoning of "the source repository is consistent" IMO defeats that point.
>
> What I would on the other hand welcome would be to track such "rebuild only revbumps" separately per architecture. Because right now we often bump the revision due to an architecture (or architecture repo) specific issue and cause a rebuild for all other architectures where such a rebuild is not necessary at all. This is again wasteful and it would be nice to avoid.

**Comment by waddlesplash** [comment] 2018-08-03 13:35
+1 to what @alaviss said.

**Comment by kallisti5** [comment] 2024-09-10 23:35
This one seems no longer relevant with the new direction of major versions in package names.  closing

**Closed by kallisti5** 2024-09-10 23:35 UTC
Labels: feedback-needed
