### ISSUE TITLE
descriptor 'lower' requires a 'str' object but received a 'unicode'

### ISSUE THREAD

**Issue by waddlesplash** [haikuports/haikuporter#82] opened 2016-02-27 01:13 UTC
https://travis-ci.org/haikuports/haikuports/builds/112147181

**Comment by pulkomandy** [comment] 2016-02-27 07:09
Hi,
Trying to access Travis CI from Haiku crashes Web+ and won't load in NetSurf because of no JS support. So I can't see where the problem lies.
Does the travis CI runs HaikuPorter with --debug? I guess not, and without a backtrace, it's hard to tell where the problem is. Which recipes should I try?

**Comment by fbrosson** [comment] 2016-02-27 07:59
Hi,
It was for the update of libssh2 to 1.7.0 (https://github.com/haikuports/haikuports/pull/486). The error I see from Travis CI is the title of this PR:
> descriptor 'lower' requires a 'str' object but received a 'unicode'

**Comment by pulkomandy** [comment] 2016-02-27 08:28
That recipe builds just fine here. Does this happen at some other step?
There are still some "str.lower" used (I think when creating repository files or something), maybe replacing them with "unicode.lower" would work, but I don't want to make the change blindly if I can't reproduce the problem.

**Comment by fbrosson** [comment] 2016-02-27 09:54
On my side libssh2-1.7.0-1 also builds fine (even if I invoke haikuporter _without_ **`--no-git-repo`**). Not a single error. _Just_ a warning, completely unrelated:
> configure: WARNING: secure clearing/zeroing of memory is not supported by the selected crypto backend

BTW, I'm using a local build of openssl, 1.0.2f, because the latest hpkg on packages.haiku-os.org is slightly outdated (1.0.2e).

Is Travis CI using the default haikuporter or the one from Git? Because I am also able to build using /bin/haikuporter but only if I also specify **`--no-source-packages`**. If I try without that switch then I get this error:
> [Errno -2147459069] No such file or directory: '/data/haikuports/repository/libssh2_source-1.7.0.DependencyInfo'

Could this be due to https://depot.haiku-os.org/ not being available right now?
> Service Unavailable
> The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

**Comment by pulkomandy** [comment] 2016-03-03 09:58
Should be fixed now.

**Closed by pulkomandy** 2016-03-03 09:58 UTC

**Comment by ed-dismantle** [comment] 2016-07-21 13:56
FYI, I got this problem when doing a --lint. I fixed it by replacing a "str.lower" with "unicode.lower" in Main.py on line 773. So the problem isn't completely fixed yet!

**Comment by mmuman** [comment] 2016-07-24 20:41
And now again, having a 'ç' in my PACKAGER name breaks everything 😒

**Comment by fbrosson** [comment] 2016-07-24 21:13
The easy (but dirty) workaround I've been using (on x86_gcc2 only) is:
export PYTHONIOENCODING=utf-8

**Comment by mmuman** [comment] 2016-07-24 21:24
It's not the best way though...
http://stackoverflow.com/questions/11741574/how-to-print-utf-8-encoded-text-to-the-console-in-python-3

**Comment by mmuman** [comment] 2016-07-24 21:34
Oh, actually, it was triggered because I exported LC_ALL=C to get English errors.
Still, it's quite fragile this way...

**Comment by fbrosson** [comment] 2016-07-24 21:51
Thanks for the info and pointers.
BTW, I only **`export PYTHONIOENCODING=utf-8`** when I need to build a recipe which has non ascii chars in some of its fields, like the COPYRIGHT of net-libs/libupnp (which has an **`é`**).
For some (unknown) reason (to me) it only happens on x86_gcc2.

**Comment by mmuman** [comment] 2016-07-27 22:26
FWIW, latest bash_completion tar.xz fails to uncompress with a codec error too (unrelated to console, it's a tarfile issue).
