### ISSUE TITLE
buildmaster slave builds with duplicate dependency packages 

### ISSUE THREAD

**Issue by korli** [haikuports/haikuporter#132] opened 2017-08-04 10:29 UTC
aus http://vmpkg.haiku-os.org/master/x86_gcc2/buildruns/40/output/builds/375.log

```
	/Media/Source/builder/x86_gcc2/packages/libicns-0.8.1-3-x86_gcc2.hpkg
	/Media/Source/builder/x86_gcc2/packages/libiconv-1.13.1-9-x86_gcc2.hpkg
	/Media/Source/builder/x86_gcc2/packages/libpng16-1.6.20-2-x86_gcc2.hpkg
	/Media/Source/builder/x86_gcc2/packages/libpng16-1.6.31-1-x86_gcc2.hpkg
	/Media/Source/builder/x86_gcc2/packages/libpng16_devel-1.6.31-1-x86_gcc2.hpkg
	/Media/Source/builder/x86_gcc2/packages/libsolv-0.3.0_haiku_2014_12_22-1-x86_gcc2.hpkg
	/Media/Source/builder/x86_gcc2/packages/libwebp-0.6.0-1-x86_gcc2.hpkg
```

buildmaster.log
```
2017-08-04 07:54:21,626: portstree head is at 3d2fa9083266d694cc362c874852376e513084e8
2017-08-04 07:54:27,908: scheduling build of pngcrush-1.8.12
2017-08-04 07:54:27,909: starting build 375, pngcrush-1.8.12 on builder mmlr_x86_gcc2
2017-08-04 07:55:01,414: build 375, pngcrush-1.8.12 succeeded
2017-08-04 07:55:01,414: package pngcrush-1.8.12 became available
2017-08-04 07:55:01,414: package pngcrush_source-1.8.12 became available
2017-08-04 07:55:01,421: finished with status: complete
```

It's like obsolete packages aren't removed.

**Comment by mmlr** [comment] 2017-08-06 22:54
The old libpng version comes from the set of initial packages, so they can't really be obsoleted. I have not yet figured why it pulls in the old version given that the new one should satisfy the requires. Since these builds I have separated out the initial packages completely, they are now provided as system packages as their own repository. This might already solve the issue, but I will have to try and reproduce before and after the change.

**Comment by kallisti5** [comment] 2024-09-10 23:57
This seems like no longer an issue. Resolving

**Closed by kallisti5** 2024-09-10 23:57 UTC
