### ISSUE TITLE
Can't Extract Source Code in Deep Directories

### ISSUE THREAD

**Issue by agmsmith** [haikuports/haikuporter#103] opened 2016-12-02 00:01 UTC
If the source code is more than one directory deep from the top of the source archive file (at least in .zip files), then HaikuPorter crashes in Utils.py.  For example:

SOURCE_URI="https://public.msli.com/lcs/beshare/BeShare2.28.zip"
CHECKSUM_SHA256="192a9dd2989433d6c27ff20047ca82814b96072fa9f72c605c0dbccd9b4da9d2"
SOURCE_DIR="BeShare/source"

  File "/boot/home/haikuporter/HaikuPorter/Source.py", line 197, in unpack
    self.sourceExportSubdir)
  File "/boot/home/haikuporter/HaikuPorter/SourceFetcher.py", line 200, in unpack
    foldSubDir)
  File "/boot/home/haikuporter/HaikuPorter/SourceFetcher.py", line 87, in unpackFile
    unpackArchive(fetchTarget, sourceBaseDir, actualSubDir)
  File "/boot/home/haikuporter/HaikuPorter/Utils.py", line 139, in unpackArchive
    if os.path.normpath(name).startswith(subdir)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 24: ordinal not in range(128)

**Comment by korli** [comment] 2017-02-20 11:49
Have you tried with "if os.path.normpath(name.decode("utf-8")).startswith(subdir)"?

**Comment by pulkomandy** [comment] 2018-08-12 09:57
Duplicate of #30.

**Closed by pulkomandy** 2018-08-12 09:57 UTC
